/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WhyLeadtionRouteImport } from './routes/why-leadtion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyLeadtionRoute = WhyLeadtionRouteImport.update({
  id: '/why-leadtion',
  path: '/why-leadtion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/services': typeof ServicesRoute
  '/why-leadtion': typeof WhyLeadtionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/services': typeof ServicesRoute
  '/why-leadtion': typeof WhyLeadtionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/services': typeof ServicesRoute
  '/why-leadtion': typeof WhyLeadtionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/how-we-work' | '/services' | '/why-leadtion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/how-we-work' | '/services' | '/why-leadtion'
  id:
    '__root__' | '/' | '/about' | '/how-we-work' | '/services' | '/why-leadtion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  ServicesRoute: typeof ServicesRoute
  WhyLeadtionRoute: typeof WhyLeadtionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-leadtion': {
      id: '/why-leadtion'
      path: '/why-leadtion'
      fullPath: '/why-leadtion'
      preLoaderRoute: typeof WhyLeadtionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  ServicesRoute: ServicesRoute,
  WhyLeadtionRoute: WhyLeadtionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
